#!/usr/bin/env bash

# The 'log' commnad captures and logs the current state of a specified GitHub
# project 'TARGET_PROJECT_TITLE' into a JSON file for archival or potential
# analysis purposes. Depends on the 'user_config.sh' file.

set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/soc-lib.sh"
source "${SCRIPT_DIR}/soc-lib-gh.sh"

# If exist, source the configuration files
if [[ -f 'user_config.sh' && -f 'source_config.sh' && -f 'system_config.sh' ]]; then
  source user_config.sh
  source source_config.sh
  source system_config.sh
else
  echo "${WRN} The 'user_config.sh', 'source_config.sh' and/or 'system_config.sh' "
  echo "file is missing. Please run the 'gh soc init' command to create the "
  echo "missing file(s)."
  exit 1
fi

# Silently validate global variables before all functions except 'init' and
# 'precheck'
precheck 0

# Check if the user has the required token scopes defined in the
# 'GH_TOKEN_SCOPES' in th 'system_config.sh' file. The command 'unsync'
# requires the 'delete_repo' scope for repository deletion and the 'project'
# scope for project deletion. For logging the project, we need the
# 'read:project' scope, but other commands require more permissions. For
# example, the 'project' scope is required by 'open' command to link the
# project to a team, by the 'sync' command to create the project, and the
# 'close' command to close the project. The 'open' command requires the
# 'write:org' scope, while the 'invite', 'disinvite', and 'delete' commands
# require the 'admin:org' scope.
check_if_gh_has_required_token_scopes

log() {

  echo 'Running get_project_data_as_json()'
  get_project_data_as_json
}

log