#!/usr/bin/env bash

# soc-gh-status: Lists repositories assigned to the team via GitHub CLI (gh).
# Usage: soc status

# shellcheck source=soc-lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib.sh"
# shellcheck source=soc-lib-gh.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib-gh.sh"

source_config_files
precheck 0
check_if_gh_has_required_token_scopes

status
