#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/gh-soc"

# If exist, source the configuration files
if [[ -f 'user_config.sh' && -f 'source_config.sh' && -f 'system_config.sh' ]]; then
  source user_config.sh
  source source_config.sh
  source system_config.sh
else
  echo "${WRN} The 'user_config.sh', 'source_config.sh' and/or 'system_config.sh' "
  echo "file is missing. Please run the 'gh soc init' command to create the "
  echo "missing file(s)."
  exit 1
fi

# Silently validate global variables before all functions except 'init' and
# 'precheck'
precheck 0

# Check if the user has the required token scopes defined in the
# 'GH_TOKEN_SCOPES' in th 'system_config.sh' file. The command 'unsync'
# requires the 'delete_repo' scope for repository deletion and the 'project'
# scope for project deletion. For logging the project, we need the
# 'read:project' scope, but other commands require more permissions. For
# example, the 'project' scope is required by 'open' command to link the
# project to a team, by the 'sync' command to create the project, and the
# 'close' command to close the project. The 'open' command requires the
# 'write:org' scope, while the 'invite', 'disinvite', and 'delete' commands
# require the 'admin:org' scope.
check_if_gh_has_required_token_scopes

unsync() {
  # Aborts the script when the first error is detected.
  set -o errexit

  local unsync_from="$1"

  # Disable the script's abort-on-first-error feature.
  set +o errexit

  if [[ "${unsync_from}" == 'project' || "${unsync_from}" == '' ]]; then
    # Asking the user for confirmation for removing the project
    echo -n "${WRN} Are you sure you want to remove the ${TARGET_PROJECT_TITLE}"
    echo " project from the organization '${GH_ORG_NAME}'? (no/yes) [no]:"
    read user_confirm

    if [[ "${user_confirm}" == 'yes' ]]; then
      echo 'Running delete_project()'
      delete_project
    fi
  fi

  if [[ "${unsync_from}" == 'repos' || "${unsync_from}" == '' ]]; then
    # Aborts the script when the first error is detected.
    set -o errexit
    # Target repositories validation
    # Check if the target repositories exist so that we can delete them.
    echo 'Running check_if_repos_exist()'
    check_if_repos_exist "${GH_ORG_NAME}" \
                         "TARGET_REPOS" \
                         "${TARGET_REPOS[@]}"

    # Disable the script's abort-on-first-error feature.
    set +o errexit

    # Asking the user for confirmation for removing all repos
    echo -n "${WRN} Are you sure you want to remove all "
    echo "repositories listed in 'TARGET_REPOS' array: "
    printf "%s\n" "${TARGET_REPOS[@]}"
    echo "from the organization '${GH_ORG_NAME}'? (no/yes) [no]:"
    read user_confirm

    if [[ "${user_confirm}" == 'yes' ]]; then
      echo 'Running delete_repositories()'
      delete_repositories
    fi
  fi
}

main "unsync" "$@"