#!/usr/bin/env bash

# soc-gh-open: Opens a course (creates team, links project, configures repos)
# using GitHub CLI (gh).
# Usage: soc open

# shellcheck source=soc-lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib.sh"
# shellcheck source=soc-lib-gh.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib-gh.sh"

source_config_files
precheck 0
check_if_gh_has_required_token_scopes

open
