#!/usr/bin/env bash

# soc-gh-log: Logs the current state of the project to a JSON file via GitHub CLI (gh).
# Usage: soc log

# shellcheck source=soc-lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib.sh"
# shellcheck source=soc-lib-gh.sh
. "$(dirname "${BASH_SOURCE[0]}")/soc-lib-gh.sh"

source_config_files
precheck 0
check_if_gh_has_required_token_scopes

log
